name: Linter

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Check out the repository first.
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        # This is important to fetch the changes to the previous commit
        fetch-depth: 0
    - uses: creyD/prettier_action@v3.0
      with:
        # prettier CLI arguments.
        args: --check "meme-cash-frontend/**/*.{js,css,html,less,scss,jsx}"
        only_changed: True
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
